# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdd826af630d766b9b982a65f489eec986324a3d6036b1fbed407d1a65f7971c65569e917413904f612596d01538688073a349322423237ec7dcd2c4fa550b67

test:
  secret_key_base: 8c84a5ccad442249382a5b97877ae1e227141d0610b8659291d32e13fc6192c8999d0ff4a76d5bbf3ca62a736165f83c367cc684b895196e227b7d7757519a8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
